version: "3.9"

services:
  app:
    image: ghcr.io/safepath-as/greentechsee-2024/app:latest
    networks:
      - nginx-proxy-network
    restart: always
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}
      - API_URL=${API_URL}
  api:
    image: ghcr.io/safepath-as/greentechsee-2024/api:latest
    networks:
      - nginx-proxy-network
    restart: always
    environment:
      - VIRTUAL_HOST=${API_HOST}
      - LETSENCRYPT_HOST=${API_HOST}

networks:
  nginx-proxy-network:
    external: true
