version: "3.9"

services:
  app:
    image: ghcr.io/safepath-as/greentechsee-2024/app:latest
    networks:
      - nginx-proxy-network
    restart: always
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}
  api:
    image: ghcr.io/safepath-as/greentechsee-2024/api:latest
    networks:
      - nginx-proxy-network
    restart: always
    environment:
      - VIRTUAL_HOST=${API_HOST}
      - LETSENCRYPT_HOST=${API_HOST}
  database:
    image: postgres:13.3
    command: postgres -c 'max_connections=50'
    container_name: database
    networks:
      - nginx-proxy-network
    environment:
      POSTGRES_USER: greentechsee
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: greentechsee
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:

networks:
  nginx-proxy-network:
    external: true
