name: Create and publish API
on:
  push:
    paths:
      - 'api/**'
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/safepath-as/greentechsee-2024

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Api
        uses: docker/build-push-action@v3
        with:
          context: api
          push: true
          tags: ${{ env.REGISTRY }}/api
