name: Create and publish Docker images
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io/Safepath-AS/greentechsee-2024

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push App
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ${{ env.REGISTRY }}/app
